name: API Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  hello:
    uses: ./.github/workflows/hello.yml
    with:
      actor: ${{ github.actor }}

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Run API Tests
        run: |
          cd ./bruno/horoscope-api/
          bru run --env prod --reporter-html results.html

      - name: Upload Test Results
        uses: actions/upload-artifact@v5
        with:
          name: test-results
          path: ./bruno/horoscope-api/results.html
